- name: Install Docker
  become: true
  ansible.builtin.yum:
    name: docker-{{ docker_version }}
    state: present

- name: Enable and start Docker
  become: true
  ansible.builtin.systemd:
    name: docker
    state: started
    enabled: true

- name: Create user
  become: true
  ansible.builtin.user:
    name: operator
    groups: docker
    append: true

- name: Validate
  become: true
  become_user: operator
  community.docker.docker_container:
    name: test
    detach: false
    image: hello-world
  register: docker

- name: Debug
  ansible.builtin.debug:
    var: docker.container.Output
